// client/src/components/grid/cells/EditableCell.vue
<template>
  <div 
    class="relative w-full h-full min-h-[40px] flex items-center"
    :class="cellClass"
    @click="startEdit"
  >
    <!-- Display Mode -->
    <div 
      v-if="!isEditing" 
      class="w-full px-2 py-1 cursor-pointer hover:bg-gray-50 dark:hover:bg-gray-800 rounded"
      :class="{ 'opacity-50': !isEditable }"
    >
      <component 
        :is="displayComponent" 
        :value="displayValue" 
        :column="column"
      />
    </div>

    <!-- Edit Mode -->
    <div v-else class="w-full px-2 py-1">
      <component
        :is="editComponent"
        v-model="editValue"
        :column="column"
        :error="error"
        @save="onCommit"
        @cancel="onCancel"
        @keydown.enter="onCommit"
        @keydown.escape="onCancel"
      />
    </div>

    <!-- Loading Indicator -->
    <q-spinner
      v-if="isCellLoading"
      size="16px"
      class="absolute top-1 right-1"
      color="primary"
    />

    <!-- Error Indicator -->
    <q-icon
      v-else-if="error"
      name="error"
      size="16px"
      class="absolute top-1 right-1 text-negative"
    >
      <q-tooltip>{{ error }}</q-tooltip>
    </q-icon>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, watch, nextTick } from 'vue'
import { ColumnConfig } from '@/lib/grid/types'
import { useGridUpdate } from '@/composables/useGridUpdate'
import { useAuthStore } from '@/lib/auth/store'

// Cell display components
import StringDisplay from './displays/StringDisplay.vue'
import NumberDisplay from './displays/NumberDisplay.vue'
import BooleanDisplay from './displays/BooleanDisplay.vue'
import DateDisplay from './displays/DateDisplay.vue'
import SelectDisplay from './displays/SelectDisplay.vue'

// Cell edit components
import StringEdit from './editors/StringEdit.vue'
import NumberEdit from './editors/NumberEdit.vue'
import BooleanEdit from './editors/BooleanEdit.vue'
import DateEdit from './editors/DateEdit.vue'
import SelectEdit from './editors/SelectEdit.vue'

const props = defineProps<{
  value: any
  rowId: string
  column: ColumnConfig
  width: number
}>()

const editValue = ref(props.value)
const isEditing = ref(false)
const error = ref<string | null>(null)

const updateMutation = useGridUpdate()
const authStore = useAuthStore()

// Check if this specific cell is updating
const isCellLoading = computed(() => 
  updateMutation.isCellUpdating(props.rowId, props.column.id)
)

// Sync editValue when prop changes (e.g., from rollback)
watch(() => props.value, (newValue) => {
  editValue.value = newValue
})

// Permissions
const hasPermission = computed(() => 
  !props.column.requiredPermissions || 
  props.column.requiredPermissions.includes(authStore.user.role)
)

const isEditable = computed(() => 
  props.column.editable && hasPermission.value
)

// Display value formatting
const displayValue = computed(() => {
  if (props.value === null || props.value === undefined) return ''
  return props.value
})

// Component selection based on column type
const displayComponent = computed(() => {
  switch (props.column.type) {
    case 'number': return NumberDisplay
    case 'boolean': return BooleanDisplay
    case 'date': return DateDisplay
    case 'select': return SelectDisplay
    default: return StringDisplay
  }
})

const editComponent = computed(() => {
  switch (props.column.type) {
    case 'number': return NumberEdit
    case 'boolean': return BooleanEdit
    case 'date': return DateEdit
    case 'select': return SelectEdit
    default: return StringEdit
  }
})

// Cell styling
const cellClass = computed(() => {
  const classes = []
  if (isEditing.value) classes.push('editing')
  if (!isEditable.value) classes.push('readonly')
  if (error.value) classes.push('error')
  return classes.join(' ')
})

// Validation
const validate = (val: any): string | null => {
  if (props.column.validator) {
    return props.column.validator(val)
  }
  return null
}

// Actions
const startEdit = () => {
  if (!isEditable.value) return
  isEditing.value = true
  error.value = null
  
  nextTick(() => {
    // Focus the input element
    const input = document.activeElement?.querySelector('input, select, textarea') as HTMLElement
    input?.focus()
  })
}

const onCommit = () => {
  const validationError = validate(editValue.value)
  if (validationError) {
    error.value = validationError
    return
  }
  
  error.value = null
  isEditing.value = false
  
  if (editValue.value !== props.value) {
    updateMutation.mutate({ 
      rowId: props.rowId, 
      columnId: props.column.id, 
      value: editValue.value 
    })
  }
}

const onCancel = () => {
  isEditing.value = false
  editValue.value = props.value
  error.value = null
}
</script>

<style lang="sass" scoped>
.editing
  background-color: rgba(25, 118, 210, 0.1)
  border: 1px solid #1976d2

.readonly
  cursor: not-allowed

.error
  background-color: rgba(244, 67, 54, 0.1)
  border: 1px solid #f44336
</style>

// client/src/components/grid/cells/EditableCell.tsx
import React, { useState, useEffect, useRef } from "react";
import { cn } from "@/lib/utils";
import { ColumnConfig } from "@/lib/grid/types";
import { useGridUpdate } from "@/lib/grid/hooks";
import { useAuthStore } from "@/lib/auth/store";
import { AlertCircle, Check, X } from "lucide-react";

interface EditableCellProps {
  value: any;
  rowId: string;
  column: ColumnConfig;
  width: number;
}

export const EditableCell = ({ value: initialValue, rowId, column, width }: EditableCellProps) => {
  const [value, setValue] = useState(initialValue);
  const [isEditing, setIsEditing] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const updateMutation = useGridUpdate();
  const { user } = useAuthStore();
  const inputRef = useRef<HTMLInputElement>(null);

  // Sync state if prop changes (e.g. from rollback)
  useEffect(() => {
    setValue(initialValue);
  }, [initialValue]);

  // Focus input when editing starts
  useEffect(() => {
    if (isEditing && inputRef.current) {
      inputRef.current.focus();
    }
  }, [isEditing]);

  const hasPermission = !column.requiredPermissions || column.requiredPermissions.includes(user.role);
  const isEditable = column.editable && hasPermission;

  const validate = (val: any) => {
    if (column.validator) {
      return column.validator(val);
    }
    return null;
  };

  const onCommit = () => {
    const validationError = validate(value);
    if (validationError) {
      setError(validationError);
      return; 
    }
    
    setError(null);
    setIsEditing(false);
    if (value !== initialValue) {
      updateMutation.mutate({ rowId, columnId: column.id, value });
    }
  };

  const onCancel = () => {
    setIsEditing(false);
    setValue(initialValue);
    setError(null);
  };

  const onKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === "Enter") {
      onCommit();
    } else if (e.key === "Escape") {
      onCancel();
    }
  };

  if (!isEditable) {
     if (column.type === "boolean") {
         return (
             <div className="flex items-center justify-center h-full w-full px-3 py-1.5">
                 <div className={cn(
                   "w-4 h-4 rounded border flex items-center justify-center opacity-60",
                   !!value ? "bg-slate-300 border-slate-400" : "border-slate-300"
                 )}>
                   {!!value && <Check className="w-3 h-3 text-slate-600" />}
                 </div>
             </div>
         )
     }
    return (
        <div className="px-3 py-1.5 h-full flex items-center truncate text-muted-foreground bg-slate-50/50 dark:bg-slate-900/50">
            {column.type === "date" && value ? new Date(value).toLocaleDateString() : String(value ?? "")}
        </div>
    );
  }

  // Boolean is always "live" (toggle immediately)
  if (column.type === "boolean") {
    return (
      <div 
        className="flex items-center justify-center h-full w-full cursor-pointer hover:bg-slate-100 dark:hover:bg-slate-800 px-3 py-1.5"
        onClick={() => {
          const newValue = !value;
          setValue(newValue);
          updateMutation.mutate({ rowId, columnId: column.id, value: newValue });
        }}
      >
        <div className={cn(
          "w-4 h-4 rounded border-2 flex items-center justify-center transition-all",
          value ? "bg-primary border-primary" : "border-input"
        )}>
          {value && <Check className="w-3 h-3 text-primary-foreground" />}
        </div>
      </div>
    );
  }

  if (isEditing) {
    if (column.type === "select" && column.options) {
        return (
             <select
                className="w-full h-full px-2 bg-white dark:bg-neutral-800 border-none focus:ring-2 focus:ring-primary focus:outline-none text-sm"
                value={value}
                onChange={(e) => setValue(e.target.value)}
                onBlur={onCommit}
                autoFocus
             >
                 {column.options.map(opt => <option key={opt} value={opt}>{opt}</option>)}
             </select>
        );
    }

    return (
      <div className="relative w-full h-full">
        <input
          ref={inputRef}
          className={cn(
              "w-full h-full px-3 bg-white dark:bg-neutral-800 border-2 focus:outline-none text-sm absolute inset-0 z-20",
              error ? "border-destructive text-destructive" : "border-primary",
              column.type === "number" && "text-right"
          )}
          type={column.type === "number" ? "number" : "text"}
          value={value}
          onChange={(e) => {
             const val = column.type === "number" ? Number(e.target.value) : e.target.value;
             setValue(val);
             if (error) setError(validate(val));
          }}
          onBlur={onCommit}
          onKeyDown={onKeyDown}
        />
        {error && (
          <div className="absolute right-2 top-1/2 -translate-y-1/2 z-30 text-destructive pointer-events-none">
            <AlertCircle className="w-4 h-4" />
          </div>
        )}
      </div>
    );
  }

  // Display Mode
  return (
    <div 
      className={cn(
          "w-full h-full px-3 py-1.5 flex items-center cursor-text hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors truncate group/cell relative",
          column.type === "number" && "justify-end font-mono",
          updateMutation.isPending && "opacity-50"
      )}
      onClick={() => setIsEditing(true)}
    >
        {column.type === "date" && value ? new Date(value).toLocaleDateString() : String(value ?? "")}
    </div>
  );
};
